gripper_len: 0.0775
clearance: .0025  # gap between end of fingers and table/mat [m]
working_pose:
  z: 0.17
  roll: 0
  pitch: 1.5708

use_numerical_ik: False

calibrate_location:
  x: 0.14
  y: -0.24

pickup_area:
  z: 0.3
  step_size: 0.05
  offset_x: 0.22
  offset_y: -0.25
  length_x: 0.25
  length_y: 0.5

scale_location:
  x: 0.15
  y: 0.23
  z: 0.015
  
cam_location:
  x: 0.37
  y: 0.21
  z: 0.0

standby_location:
  x: 0.26
  y: 0.0

discard_area:
  z: 0.05
  offset_x: 0.09
  offset_y: -0.35
  length_x: 0.08
  length_y: 0.13

